### ISSUE TITLE
Feature: labeled commands (for each saved)

### ISSUE THREAD

**Issue by mrienstra** [phitranphitranphitran/regexp-saver#13]
Would be handy to add find/replace `Commands` (that can be found in the `Command Palette`) for each saved regex. E.g. if the user has a saved regex with the label `Replace numbers with #`, then typing "Replace numbers" (or "with #" or "regexp" or "saver", etc.) in the `Command Palette` would show the following `Commands`:
- RegExp Saver: Find in File: Replace numbers with #
- RegExp Saver: Find in Selection: Replace numbers with #
- RegExp Saver: Replace in File: Replace numbers with #
- RegExp Saver: Replace in Selection: Replace numbers with #

Or:
- RegExp Saver: Find "Replace numbers with #" in File
- RegExp Saver: Find "Replace numbers with #" in Selection
- RegExp Saver: Replace "Replace numbers with #" in File
- RegExp Saver: Replace "Replace numbers with #" in Selection

Willing to assist if desired.

PS: Hi! Great extension, thank you!

**Comment by phitranphitranphitran** [comment]
I think this should be possible. I won't have time for a while to work on it, so any help is definitely welcome!

Right now the commands are statically declared in the [activate function](https://github.com/phitranphitranphitran/regexp-saver/blob/master/src/extension.ts#L4). It could be updated to read from the global/workspace settings before registering commands, and register extra commands for any regexps that have the option `"registerCommand": true`.

There will also need to be an addition to the "save new" UI that asks whether or not you want to register a command for the regexp too.

Links that could be helpful:
https://code.visualstudio.com/api/references/activation-events#onView
https://code.visualstudio.com/api/extension-guides/command#creating-new-commands

PS: Thank you, glad it was useful!

**Comment by mrienstra** [comment]
@phitranphitranphitran, thanks! Alas, this doesn't appear to be possible at this time, hopefully someday! For now I'll close this.

https://github.com/microsoft/vscode/issues/1422
