### ISSUE TITLE
Can't find json file

### ISSUE THREAD

**Issue by acestronautical** [phitranphitranphitran/regexp-saver#3]
No option to open json file, and no location listed for json file

**Comment by phitranphitranphitran** [comment]
For each project the vscode settings are located in `./vscode/settings.json`.

If you open the Command Palette (Ctrl/Cmd + Shift + P) and search for "settings" there will be more options such as "Preferences: Open Settings (JSON)".

But it would be good to mention this in the README! Thanks for bringing this up

**Comment by phitranphitranphitran** [comment]
Addressed in https://github.com/phitranphitranphitran/regexp-saver/commit/7d6c61ebccf465af533780d5ff48e955c2f95010
